version: '3.8'
services:
  localstack:
    image: localstack/localstack:4.8.1
    container_name: localstack
    ports:
      - "4566:4566"  # Edge port for all services
      - "4571:4571"  # Optional: Lambda executor port
    environment:
      - SERVICES=s3,lambda,dynamodb,cloudfront,iam,sts
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/tmp/localstack"
